version: "3.9"
services:
  database:
    container_name: database
    image: mysql:8.0.33
    restart: always
    privileged: true
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3308:3306"
    command: --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    privileged: true
    ports:
      - "8888:80"
    restart: always
    environment:
      PMA_HOST: database
      UPLOAD_LIMIT: 50M
    depends_on:
      - database
